# 公共复用数据
common:
  kafka: &commonKafkaBroker
    broker:
      - mkafka1:9092
      - mkafka2:9092
    group: &commonKafkaGroup
      mcleaner_24
  redis: &commonRedisGroup
    ip: mredis
    port: 60379
    auth: uXUxGIyprkel1nYWhCyoCYAT4CNCUW2mXkVcDfhTqetnYSD7
    db: 11

# app相关信息
app:
  id: 24
  name: mcleaner

# kafka相关信息
kafka:
  consumer:
    <<: *commonKafkaBroker
    # 自身属性覆盖公共属性
    broker:
      - mkafka1:9092
      - mkafka2:9092
    group: *commonKafkaGroup

  producer:
    <<: *commonKafkaBroker


# redis相关信息
redis:
  store:
    <<: *commonRedisGroup
  setting:
    <<: *commonRedisGroup
  settingTools:
    <<: *commonRedisGroup
    ip: mredis
    db: 1